### ISSUE TITLE
having trouble installing on opensuse

### ISSUE THREAD

**Issue by Un1q32** [Stunkymonkey/nautilus-open-any-terminal#158]
I installed from pip, and installed `python312-nautilus` from repos, running `nautilus -q` shows this in terminal
```
Traceback (most recent call last):
  File "/home/uniq/.local/share/nautilus-python/extensions/nautilus_open_any_terminal.py", line 26, in <module>
    require_version("Gtk", "4.0")
  File "/usr/lib64/python3.11/site-packages/gi/__init__.py", line 125, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Gtk not available for version 4.0
```
I assume there's just a dependency I need to install, if you could help me out by telling me what it is I would greatly appreciate it

**Comment by lvxnull** [comment]
Did you check if this issue exists on the latest master?

**Comment by Un1q32** [comment]
> Did you check if this issue exists on the latest master?

master has a different error
```
/usr/lib64/python3.11/site-packages/gi/module.py:172: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  g_type = info.get_g_type()
/usr/lib64/python3.11/site-packages/gi/module.py:172: Warning: g_once_init_leave_pointer: assertion 'result != 0' failed
  g_type = info.get_g_type()
/usr/lib64/python3.11/site-packages/gi/module.py:207: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  type_ = g_type.pytype
```
then it hangs forever, opening nautilus is impossible until I uninstall the extention

**Comment by lvxnull** [comment]
What's the output of `zypper info nautilus`?

**Comment by Un1q32** [comment]
```
Information for package nautilus:
---------------------------------
Repository     : repo-oss
Name           : nautilus
Version        : 46.0-1.2
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 1.6 MiB
Installed      : Yes
Status         : up-to-date
Source package : nautilus-46.0-1.2.src
Upstream URL   : https://wiki.gnome.org/Apps/Nautilus
Summary        : File Manager for the GNOME Desktop
Description    : 
    Nautilus is the file manager for the GNOME desktop.
Requires       : [20]
    libc.so.6(GLIBC_2.38)(64bit)
    libglib-2.0.so.0()(64bit)
    libgobject-2.0.so.0()(64bit)
    libgio-2.0.so.0()(64bit)
    libcairo.so.2()(64bit)
    libgdk_pixbuf-2.0.so.0()(64bit)
    libpango-1.0.so.0()(64bit)
    libgmodule-2.0.so.0()(64bit)
    libgtk-4.so.1()(64bit)
    libadwaita-1.so.0()(64bit)
    libadwaita-1.so.0(LIBADWAITA_1_0)(64bit)
    libgraphene-1.0.so.0()(64bit)
    libtracker-sparql-3.0.so.0()(64bit)
    libportal.so.1()(64bit)
    libnautilus-extension.so.4()(64bit)
    libgnome-desktop-4.so.2()(64bit)
    libgnome-autoar-0.so.0()(64bit)
    libportal-gtk4.so.1()(64bit)
    libcloudproviders.so.0()(64bit)
    tracker-miner-files >= 2.99
```

**Comment by lvxnull** [comment]
Please install `typelib-1_0-Gtk-4_0` and see if it works.

**Comment by Un1q32** [comment]
that worked
